---
title: "Test the core functions"
author: "IMA tumor modeling team"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r}
suppressMessages(source("ams_initialize_script.R"))
suppressMessages(library(RxODE))
suppressMessages(library(dplyr))
suppressMessages(source("AFIRT_calculation.R"))
suppressMessages(source("ivsc_4cmtct_shedct.R"))
```

### Run AFIRT sensitivity analysis WRT dose.nmol on a parameter file
#### Specific parameter file is changed just below

```{r}
d <- read_excel("../data/ivsc_4cmtct_shedct_param.xlsx", 1)
#d <- read_excel("../data/ModelF_Atezolizumab_Params.xlsx", 1)
param.as.double = d$Value
names(param.as.double) = d$Parameter

dose.nmol.range = lseq(1, 1e5, 6)

model = ivsc_4cmtct_shedct()

tmax = 200
tau  = 1
compartment = 2

sample.points = c(seq(-7, tmax, 0.1), 10^(-3:0)) # sample time, increment by 0.1

df_sim = data.frame() # put all simulations for different dose into one data frame
for (dose.nmol in dose.nmol.range){
  row = lumped.parameters.simulation(model,
    param.as.double, dose.nmol, tmax, tau, compartment)
  df_sim = rbind(df_sim, row)
}
df_sim$Dose = dose.nmol.range

df_thy = data.frame() # put all theoretical calculations of lumped parameters at different dose together
for (dose.nmol in dose.nmol.range){
  row = lumped.parameters.theory(param.as.double, dose.nmol, tau)
  df_thy = rbind(df_thy, row)
}
df_thy = df_thy %>%
  mutate(Dose = dose.nmol.range,
         AFIRT = AFIRT.Kss)

#Dose = as.data.frame(dose.nmol.range)
#AFIRT_sim = as.data.frame(df_sim$AFIRT)
#AFIRT_Kd= as.data.frame(df_thy$AFIRT.Kd)
#AFIRT_Kss = as.data.frame(df_thy$AFIRT)

```
#### Print out the data frame
```{r}
#AFIRT = data.frame(Dose, AFIRT_Kd, AFIRT_Kss, AFIRT_sim)
#names(AFIRT)= c("Dose","AFIRT_Kd", "AFIRT_Kss", "AFIRT_sim")
df_compare = bind_rows(df_thy,df_sim)
df_compare = df_compare %>%
  arrange(Dose,type)
kable(df_compare)
```

#### Make the plot
```{r}
#names = names(AFIRT)
#data = AFIRT %>% gather(key, value, -c(get(names[1])))
g = ggplot(df_compare, aes(Dose, AFIRT, group=type, color=type)) +
  scale.x.log10() +
  scale.y.log10() +
  geom_line() +
  geom_point()
print(g)
```

```{r}
knit_exit() #this stops the Rmarkdown early
```

### Run AFIRT sensitivity analysis WRT dose.nmol on the parameter file
#### ModelF_Atezolizumab_Params.xlsx

```{r}

d <- read_excel("../data/ModelF_Atezolizumab_Params.xlsx", 1)
param.as.double = d$Value
names(param.as.double) = d$Parameter

dose.nmol.range = lseq(1, 100000, 20)


df_sim = data.frame() # put all simulations for different dose into one data frame
for (dose.nmol in dose.nmol.range){
  row = lumped.parameters.simulation(model,
    param.as.double, dose.nmol, tmax, tau, compartment)
  df_sim = rbind(df_sim, row)
}

df_thy = data.frame() # put all theoretical calculations of lumped parameters at different dose together
for (dose.nmol in dose.nmol.range){
  row = lumped.parameters.theory(param.as.double, dose.nmol, tau)
  df_thy = rbind(df_thy, row)
}

Dose = as.data.frame(dose.nmol.range)
AFIRT_sim = as.data.frame(df_sim$AFIRT)
AFIRT_Kd= as.data.frame(df_thy$AFIRT.Kd)
AFIRT_Kss = as.data.frame(df_thy$AFIRT)

```
#### Print out the data frame
```{r}
AFIRT = data.frame(Dose, AFIRT_Kd, AFIRT_Kss, AFIRT_sim)
names(AFIRT)= c("Dose","AFIRT_Kd", "AFIRT_Kss", "AFIRT_sim")
kable(AFIRT)
```

#### Make the plot
```{r}
names = names(AFIRT)
data = AFIRT %>% gather(key, value, -c(get(names[1])))
g = ggplot(data, aes(Dose, value, color=key)) +
  scale.x.log10() +
  scale.y.log10() +
  geom_line() +
  geom_point()
print(g)
```


