---
title: "Explore The Model When Soluble Target Is Present"
author: "Hongshan Li"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---


```{r, warning=FALSE}
suppressMessages(source("ams_initialize_script.R"))
suppressMessages(source("AFIRT_calculation.R"))
suppressMessages(source("ivsc_4cmtct_shedct.R"))
```

### Set initial parameters and functions
Hongshan says: I just assume (.1, 100) x scale.mpk2nmol is a reasonable dose Bevacizumab
```{r}
dose.nmol.range = lseq(.1,100,7)*scale.mpk2nmol

model = ivsc_4cmtct_shedct()

tmax = 26*7 #days
tau  = 21   #days
compartment = 2
```
### Import parameters for Bevacizumab
```{r}
param.as.double =  read.param.file("../data/ModelF_Bevacizumab_Params.xlsx", model=model)
pdb.bevacizumab = param.as.double
p.bevacizumab = as.data.frame(t(param.as.double))
p.bevacizumab$drug = "Bevacizumab"

df_compare = compare.theory.sim(model = model,
                                param.as.double = param.as.double,
                                dose.nmol.range = dose.nmol.range,
                                tmax = tmax,
                                tau  = tau,
                                compartment = compartment)

```

