---
title: "Compare AFIRT AFIRT* and Simulation"
author: "Hongshan"
date: "June 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The goal of this task is to compare AFIRT, AFIRT* and simulation
over a range of dose
```{r}
suppressMessages(source("ams_initialize_script.R"))

dose.nmol.range = lseq(0.1, 100000, 7)
model = ivsc_4cmtct_shedct()
tmax = 26*7 #days
tau = 21 #days
compartment = 2

```

Load parameters for Atezo
```{r}
param.as.double = read.param.file("../data/ModelF_Atezolizumab_Params.xlsx")
p.atezo = as.data.frame(t(param.as.double))
```

```{r}
df_sim = data.frame() # put all simulations for different dose into one data frame
  for (dose.nmol in dose.nmol.range){
    row = lumped.parameters.simulation(model,
      param.as.double, dose.nmol, tmax, tau, compartment)
    df_sim = rbind(df_sim, row)
  }

df_thy = data.frame() # put all theoretical calculations of lumped parameters at different dose together
for (dose.nmol in dose.nmol.range){
  row = lumped.parameters.theory(param.as.double=param.as.double, 
                                dose.nmol=dose.nmol, 
                                tau=tau)
  df_thy = rbind(df_thy, row)
}

df_thy$Dose = dose.nmol.range

```
Make a data frame with 4 columns:
Dose, AFIRT.Kssd, AFIRT_, AFIRT.sim
```{r}
df_compare = df_thy %>%
  select(Dose, AFIRT.Kssd, AFIRT.Kssd_)

df_compare$AFIRT.sim = df_sim$AFIRT.sim
```
Plot the data
```{r}
df_plot = df_compare %>%
  gather(AFIRT, value, -Dose)

g = ggplot(df_plot, aes(Dose, value, group=AFIRT, color=AFIRT)) + 
  geom_line() + 
  geom_point()+
  scale.x.log10() +
  scale.y.log10()

print(g)
```








